### ISSUE TITLE
[Dev][관리자용 대시보드] 관리자용 대시보드(메인페이지로 이동) - front

### ISSUE THREAD

**Issue by MyM999** [itavita08/..............#34]
기술셋
React

요구사항
- 관리자페이지에서 메인페이지버튼 클릭시 메인페이지로 이동(url)

예외처리
- back에서 받은 에러메세지 출력

**Comment by itavita08** [comment]
- ELK에서 Reack 차트 API사용 으로 변경
- 사이드 바에서 관리자 페이지로 이동 시 back에서 데이터 응답받아 차트 그리기
