### ISSUE TITLE
[DEV] 피그마 와이어프레임

### ISSUE THREAD

**Issue by MyM999** [itavita08/..............#7]
** 로그인 페이지 **

** 회원 가입 페이지 **

** 메인 페이지 **

** 검색 결과 페이지 **

** 개인 공간 (블로그)  하위 페이지**

- 개인정보 확인 및 수정 페이지 **

- 게시물 상세 페이지 **

- (그림 일기) 포스팅 페이지**

** 개인 공간 관리자 메인 페이지

페이지 폼 기본설계

**Comment by cso6005** [comment]
11
